---
- name: Play A
  hosts: localhost 
  gather_facts: false
  vars: 
    device: "router"

  tasks:
    - name: Hello World
      debug:
        msg: "Hello World"

    - name: print vars
      debug:
        var: device

    - name: Set fact for source ip
      set_fact:
        src_ip: "testing set fact for source ip"

    - name: Display set fact value
      debug:
        var: src_ip

# - name: Play B
# - name: Play C